apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: dash
    suite: pachyderm
  name: dash-lb
  namespace: pachyderm
spec:
  ports:
  - name: dash-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc-proxy-http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: dash
    suite: pachyderm
  sessionAffinity: None
  type: LoadBalancer
