apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"dash","suite":"pachyderm"},"name":"dash","namespace":"pachyderm"},"spec":{"ports":[{"name":"dash-http","nodePort":30080,"port":8080,"targetPort":0},{"name":"grpc-proxy-http","nodePort":30081,"port":8081,"targetPort":0}],"selector":{"app":"dash","suite":"pachyderm"},"type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2019-08-06T01:30:26Z"
  labels:
    app: dash
    suite: pachyderm
  name: dash
  namespace: pachyderm
  resourceVersion: "4989813"
  selfLink: /api/v1/namespaces/pachyderm/services/dash
  uid: c46514b8-b7e9-11e9-a2a0-cad3a4f30f15
spec:
  clusterIP: 10.0.229.248
  externalTrafficPolicy: Cluster
  ports:
  - name: dash-http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc-proxy-http
    nodePort: 30081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: dash
    suite: pachyderm
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
