FROM debian

RUN apt-get update && apt-get install -y curl
RUN curl -o /tmp/pachctl.deb -L https://github.com/pachyderm/pachyderm/releases/download/v1.9.2/pachctl_1.9.2_amd64.deb &&  dpkg -i /tmp/pachctl.deb

RUN curl -o grpcurl_1.3.1_linux_x86_64.tar.gz -L https://github.com/fullstorydev/grpcurl/releases/download/v1.3.1/grpcurl_1.3.1_linux_x86_64.tar.gz &&   tar -xvfz grpcurl_1.3.1_linux_x86_64.tar.gz
 
