FROM debian

RUN apt-get update && apt-get install -y curl
RUN curl -o /tmp/pachctl.deb -L https://github.com/pachyderm/pachyderm/releases/download/v1.9.2/pachctl_1.9.2_amd64.deb &&  dpkg -i /tmp/pachctl.deb
